version: "3"
services:
    client:
        container_name: bug_tracker
        build: ./
        restart: always
        ports:
            - "3000:3000"
        working_dir: /app
        volumes:
            - ./:/app
        entrypoint: ["npm", "start"]
        links:
            - api
        networks:
            - webappnetwork
    api:
        container_name: bug_tracker_api
        build: ./backend
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        environment:
            - MONGO_INITDB_DATABASE=mongodb
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes:
            - ./mongo-volume:/data/db
        ports:
            - 27017:27017
        networks:
            - mongo_net
networks:
    webappnetwork:
        driver: bridge
    mongo_net:
        driver: bridge